version: '2'

services:
    api:
        restart: always
        build: ./bdcs-api-rs/
        image: weld/bdcs-api:latest
        ports:
            - 4000
        volumes:
            - bdcs-recipes-volume:/bdcs-recipes/
            - ./mddb/:/mddb/
        security_opt:
            - label:disable

    web:
        restart: always
        build: ./welder-web/
        image: weld/web:latest
        links:
            - api
        ports:
            - 80:3000

volumes:
    bdcs-recipes-volume:
        driver: local
